target 'BaseProject' do
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'Masonry'
pod 'YYKit'
pod 'IQKeyboardManager'
#bug统计
pod 'Bugly'

#友盟
#基础库
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
#统计
pod 'UMCAnalytics'
#分享
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
#rac信号量
pod 'ReactiveObjC'
#内存泄露检测工具
pod 'MLeaksFinder'
#蘑菇街组件
pod 'MGJRouter'
end
