target 'BaseProject' do
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'SDWebImage' 
pod 'AFNetworking'
pod 'Masonry'
pod 'UICKeyChainStore', '~> 2.1.0'
pod 'MLeaksFinder'
pod 'YYKit'
#pod 'Meiqia', '~> 3.4.3'
end
